### ISSUE TITLE
Tripal 4 Fields -upgrading core fields

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1414]
# Core Tripal 4 Development Task

## Branch Name: tv4g1-issue1414-[name of field you are working on]

This issue is providing an organization spot to upgrade all the core Tripal fields. Please comment here with the field you are going to upgrade and create a branch using the naming schema above to contain your work. When done, create a PR for your field.

Here is the documentation for [Tripal Fields](https://tripaldoc.readthedocs.io/en/latest/dev_guide/module_dev/fields.html)

## Fields in order of complexity

- [x] [data__sequence_checksum](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/data__sequence_checksum/data__sequence_checksum.inc) Pull #1419 closed #1607 merged
- [x] [data__sequence_length](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/data__sequence_length/data__sequence_length.inc)  Pull #1419 closed #1607 merged
- [x] [operation__analysis](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/operation__analysis/operation__analysis.inc)  Pull #1578 merged
- [x] [local__contact](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/local__contact/local_contact.inc)  Pull #1599 merged
- [x] [sep__protocol](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/sep__protocol/sep__protocol.inc) Pull #1743 merged
- [x] [uo__unit](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/uo__unit/uo__unit.inc) Pull #1680 merged
- [x] [local__source_data](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/local__source_data/local__source_data.inc) Pull #1504 merged
- [x] [data__sequence_coordinates](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/data__sequence_coordinates/data__sequence_coordinates.inc)  Pull #1700 merged
- [x] [operation__analysis](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/operation__analysis/operation__analysis.inc) Pull #1578 merged
- [x] [local__contact](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/local__contact/local__contact.inc) Pull #1431 merged
- [x] [sbo__database_cross_reference](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/sbo__database_cross_reference/sbo__database_cross_reference.inc) Pull #1710 merged
- [x] [schema__alternate_name](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/schema__alternate_name/schema__alternate_name.inc) Pull #1447 closed #1650 merged
- [ ] [sbo__relationship](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc)
 * [sio__references](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/sio__references/sio__references.inc) - with a complete set of linker fields now available, this specialized field is likely no longer needed 😐

Some other fields needed are listed here https://github.com/tripal/tripal/issues/1550#issuecomment-1623912019

**Comment by dsenalik** [comment]
I am working on the local__contact field :grin:

**Comment by srobb1** [comment]
I would like to work on data__sequence_length

**Comment by spficklin** [comment]
Just FYI.... we have a new way to add fields via YAML files which is currently in PR #1413  so the documentation for fields needs to be updated.   Also, we have a new naming convention that was discussed in the Hackathon in January.  @Ferrisx4 I don't remember where that was documented, can you link to it here?

**Comment by laceysanderson** [comment]
Yes, people can just use the old way for now and we'll update the way fields are added when that PR get's merged. The naming conventions were a PR in the TripalDoc repo that I just merged. 

You can find them here: https://tripaldoc.readthedocs.io/en/latest/dev_guide/module_dev/fields.html#naming-convention
<img width="772" alt="Screen Shot 2023-02-06 at 11 51 56 AM" src="https://user-images.githubusercontent.com/1566301/217047436-15dd3cf8-9747-4e11-b434-7596d1268c2f.png">

**Comment by srobb1** [comment]
I also worked on the checksum

**Comment by srobb1** [comment]
Sukha is working on local__source_data

**Comment by srobb1** [comment]
My pull request #1419 which contains both length and md5 are ready for review.

**Comment by srobb1** [comment]
I would like to attempt schema__alternate_name next.  I have started on it and am having an error that I also get when I try to add a new chado organism reference to my gene. see issue #1432 . I used the organism field as a starting point since there are primary and foreign keys.

**Comment by dsenalik** [comment]
## ChadoAnalysisDefault field
I am creating branch `tv4g1-issue1414-ChadoAnalysisDefault` to implement the ChadoAnalysisDefault field.
This field is needed for issue #1550.

I am testing it on the phylogenetic tree content type, but we don't have a dbxref field yet, so right now you can't manually enter a tree. To be able to test, I have to temporarily do two things to allow me to create a phylotree record:
 1. `ALTER TABLE chado.phylotree ALTER COLUMN dbxref_id DROP NOT NULL;`
 2.  In `tripal_chado/src/Plugin/TripalStorage/ChadoStorage.php` line 1048 I temporarily add a `return();` to disable validation.

Then I can create a tree, and test adding and changing an analysis record.

## Pull request: #1578

**Comment by imnuvi** [comment]
Hi Team, I would like to work on data__sequence_coordinates.

**Comment by dsenalik** [comment]
I'm sorry I didn't take the time to update the field list here, that field is already being worked on in branch `tv4g1-issue1414-data__sequence_length` by [Sukha](https://github.com/pdtouch)
I think the other two are still available, as @srobb1 has not posted on `schema__alternate_name` since February.

**Comment by pdtouch** [comment]
> Hi Team, I would like to work on data__sequence_coordinates.
I am currently working on it, Will check with @laceysanderson more about it.

**Comment by imnuvi** [comment]
Thanks @dsenalik for the info, I am starting work on _schema__alternate_name_

**Comment by dsenalik** [comment]
PR #1599 implements the ChadoContactDefault field

**Comment by laceysanderson** [comment]
Thanks for all the hard work here everyone! I'm removing the "Good first issue" tag from this issue as the only remaining field listed here is the relationship field, which is a harder one. That said, if you are looking for another issue to work on, I have tagged a few more issues and expanded their descriptions with information for how to fix them :-)

**Comment by pdtouch** [comment]
Thanks for the reviews and merges. Appreciate your help.

**Comment by dsenalik** [comment]
Branch for the relationship field:
`tv4g1-issue1414-relationship-field`
