### ISSUE TITLE
Cleanup TripalStorage/ChadoStorage

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1593]
# Core Tripal 4 Development Task

## Branch Name: tv4g2-1593-chadoStorageCleanup

Today in Codefest we had a great discussion about ChadoStorage. It turns out there may be some cruft in there from the early days of development and that some functions are not being used as originally intended in the design.

## Tasks

- [x] @spficklin / @Ferrisx4 add in their changes to addTypes() to ensure property types are not being clobbered
- [x] @spficklin / @Ferrisx4 add in their changes to the values array to support associating the operation with values as needed by publishing.
- [x] Check that [TripalEntityStorageSchema](https://github.com/tripal/tripal/blob/4.x/tripal/src/Entity/TripalEntityStorageSchema.php) can be removed.
- [x] Ensure that [TripalEntity](https://github.com/tripal/tripal/blob/4.x/tripal/src/Entity/TripalEntity.php) uses add/getTypes() as designed.
- [x] Add new methods for add/getFieldDefinitions() to the TripalStorage Interface and classes.
- [x] Now that property types and field definitions are being added to the class elsewhere, remove them from the $values array passed into insert/load/update/delete/findValues() methods.

## Summary of Codefest conversation / Background for above tasks

When Stephen + Sean were working on Publishing of Chado Records, they came across some inconsistencies:

### TripalEntityStorageSchema

The first question is when are the functions in TripalEntityStorageSchema being called? They added dpms all over trying to detect this class being used and it doesn't seem to be... For example, TripalEntityStorageSchema->onFieldableEntityTypeCreate() should be called when new types for Tripal Entity are created. This should ensure that Drupal tables for this type are created... However, debugging calls in this method are not displayed on Tripal entity type creation 🤔 although the tables are created.

Discussion included remembering back to the beginning of TripalStorage development. We had hoped to override SqlContentEntityStorageSchema to handle multiple database backends as this seemed to be the point that single database assumption was added in. However, after much digging by Josh it became apparent that the assumption of a single database had leaked out of this class and throughout Drupal 😞 When this was discovered we abandoned overriding SqlContentEntityStorageSchema and instead took the approach of keeping those default sql table structures but then building the TripalStorage plugin over top to use the information in those tables to access other data backends. When this change in design was made, I believe the TripalEntityStorageSchema class should have disappeared... However it remains. Is it just a relic of bygone times or is it still connected into the functioning of TripalStorage?

### addTypes() + getTypes()

The original design of TripalStorage was built on the workflow: 
1. Add property types to the storage plugin to define the types of data being used. This would include all properties for a given database across various fields although within a single bundle. For fields this would be done by the FieldType class when it was initialized.
2. Depending on the action needed (e.g. load, insert, update, delete), the already initialized storage plugin would pass in a values array to the appropriate *Values() method. This values array would hold all the user input and any defaults from the database.
3. Then the storage plugin uses the information from the types and values to perform the requested action on the database for all fields at once. This allows multiple fields to combine to define a single record in the database and ensures that relationships between fields/records can be easily made without duplicating the information.

However, at some point during implementation, the values array mentioned in 3 above was altered to hold the property types and values as well as the field definition. This likely made programming these *Values() methods easier as everything it needed was passed in directly. However, it made addTypes() and addValues() redundant as instead of using the types set in the storage plugin, these methods used the ones they were passed directly. This causes problems when implementing findValues() as they need access to the property types in a more centralized manner which addTypes() provides...

We are going to move back towards the original design and integrate add/getTypes back into the workflow. This will also require altering of the values array to remove the property types as they are already present in the object and do not need to be passed in again.

@spficklin  / @Ferrisx4 also mentioned that there was a bug in addTypes that was causing properties with the same name to get clobbered. They will add their fix into this branch before I begin the work on addTypes.

### addFieldDefinitions() + getFieldDefinition()

I brought this up when we were discussing add/getTypes. Currently the field definition is saved for every single property in the values array. This is repetitive and could cause performance issues. Since we are moving the property types out of the values array, we should also move out the field definitions. As such we will add addFieldDefinitions() + getFieldDefinition() to the interface and implement for tripalstorage as it is backend independent.

### findValues()

Currently findValues() and deleteValues are not yet implemented. However, findValues is needed for publishing data from chado. As such, @Ferrisx4 will be implementing it as part of his PR. One change thats a bit more far reaching is that currently the operation is not supported in the values array used by the *Values() methods. This is needed for findValues(). As such, @Ferrisx4 / @spficklin are going to add their change to the values array with adds a `operation` key to support this functionality. We'll add that into this PR in order to keep things moving and reduce merge conflicts when publishing is complete.

**Comment by spficklin** [comment]
I've added in the code to this branch that @Ferrisx4 and I worked on related to the two items in the description above.

**Comment by laceysanderson** [comment]
All the tasks are complete. Now I just need to test the fields manually :-) Automated tests should be passing 🙏  Then the PR will be forth-with.

**Comment by spficklin** [comment]
Thanks @laceysanderson for the hard work on this!  I'm glad we caught this and it got fixed.
