### ISSUE TITLE
Tripal Layout TODO

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1794]
### Task Description

Since PR #1792 looks like it is a solution for issue #1615. I wanted to create a new issue with the missing functionality that is still needed.  This list is taken from the PR. 

- [ ] **Sidebar**. Create a block that can be put anywhere (not in the content section like in Tripal 3) that can provide a clickable table of contents for the Tripal entity page.  To meet accessibility constraints clicking on a link in the table of contents block should take the user directly to the spot on the page like a typical anchor.  The moving of sections like Tripal 3 does isn't ideal.
- [ ] **Support all Content Types**. Currently we only support layouts for: organism, analysis and gene, we need to create one for all of the content types provided by Tripal
- [ ] **Support more field groups**. Currently we only support two of the field group types: "details" and "field_group_table" but there are others such as "tabs", "accordian", etc.  Consider if we want more, or implement them as needed.
- [ ] **Support field types**. Using the chado field type (e.g. in the YAML as "type:chado_property_type_default" can be used to indicate all property fields go "here".) is not yet supported. The idea is that if you specify a child with a "type:" prefix then all of the fields of that type will be considered children. That's useful for properties where there are an unknown number.

### Branch Name

tv4g7-issue1794-[optional short descriptor]
