### ISSUE TITLE
Support HTML tags in content titles

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1872]
### Task Description

PR #1862 (and #1871 ) added support for wysiwyg toolbars on widgets. 
If you want to use a field in your content title, and it is set to one of the HTML modes, e.g. "Basic HTML" then the HTML tags are not interpreted in the page title.
The task is to allow this. For example, you might want italics in a gene name, genus, project name, etc.

**How to reproduce this** 
 * For the "Protocol" content type, edit the title format to include `[protocol_software]`
![2024-05-06_titleformat](https://github.com/tripal/tripal/assets/8419404/20dc3daa-8838-40ae-bf3d-3e1ec9a36742)
 * Enter a new "Protocol" and for software use some formatting, for example
![2024-05-06_software](https://github.com/tripal/tripal/assets/8419404/1d795c53-2d80-47ae-8276-e60e77a2b631)
 * When saved, the title looks like this
![2024-05-06_appearance](https://github.com/tripal/tripal/assets/8419404/2fcb7465-7ff5-45d5-af28-6a84aadda40d)

### Branch Name

tv4g7-issue1872-html-tags-in-page-titles

### Specific changes needed
  - [x] `TripalTokenParser()` should strip outer &lt;p&gt;&lt;/p&gt; tags - These are added if a field is configured to one of the HTML filters and you want to use that value in the title. Maybe we want to include italics in a gene name and show that in the title. The value will always be stored in the database table with wrapping &lt;p&gt;&lt;/p&gt; tags around it.
  - [x] Add test for the above change
  - [x] The entity list should support HTML tags. Once implemented, the organism content pages can appear like this
![20240517_entitylist](https://github.com/tripal/tripal/assets/8419404/cd25fc32-1357-4147-a670-57e4bf809af5)

  - [x] Create a hook to preprocess the title field, and convert the string value into markup. This will allow any HTML tags to be rendered.

  - [x] Create a hook to preprocess the page title block, again convert any string value into markup.

  - [x] The default organism title template can now include italics `<em>[organism_genus] [organism_species]</em> [organism_infraspecific_type] <em>[organism_infraspecific_name]</em>`
    An organism page should look like this now
![2024-05-20_allworking](https://github.com/tripal/tripal/assets/8419404/70734750-470f-4104-a6ac-aca67a217295)
