### ISSUE TITLE
Chado Buddy for Properties

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1935]
### Task Description

With Issue #1780 and PR #1844 we implement Chado Buddies for db, dbxref, cv, and cvterm tables.

We also need a Buddy for properties, so this issue will handle that, as the current api functions are waaaaay slow.
[tripal_chado/src/api/tripal_chado.property.api.php](https://github.com/tripal/tripal/blob/f64996ec000f0bbd9263f60dc62dd1e09e7cd949/tripal_chado/src/api/tripal_chado.property.api.php)

Task List
- [x] Create testing outline
- [x] Property Buddy: outline
- [x] Property Buddy: getProperty()
- [x] Property Buddy: insertProperty()
- [x] Property Buddy: updateProperty()
- [x] Property Buddy: upsertProperty()
- [x] Property Buddy: deleteProperty()

### Branch Name

tv4g2-issue1935-chado-property-buddy
