### ISSUE TITLE
Update how we install Chado to better control schema

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#2072]
### Task Description

This task came up during PR #2055. PostgreSQL 17 was consistently triggering the search_path issues that have intermittently plagued us for awhile. 

The fix in the indicated PR is effective but also means we can no longer regenerate the parts. As such, we removed the original single `default_schema-1.3.sql` file that those parts were generated from.

We started a more ideal approach which segments the original `default_schema-1.3.sql` into parts based on what schema they should go in so that we can better control the schema assignments. However, this approach was put on hold due to time constraints.

This issue is intended to remind us to finish the more ideal approach in the future when we have time :-) 

Tasks:
- [x] Segment the original `default_schema-1.3.sql` into parts based on what schema they should go in.
- [ ] Update these segments by adding "SET search_path FROM CURRENT" to all functions.
- [ ] Create all functions in the public schema. Add tests to ensure these functions act on the correct schema based on search_path settings.
- [ ] Decide if we want to continue having the non-chado schema (i.e. frange, so, genetic_code). See this core Chado discussion on this https://github.com/GMOD/Chado/issues/123
- [ ] Update the `tripal_chado/chado_schema/chunk_sql_file.php` to create the chunks from the segmented default_schema and to set the search path appropriately at the beginning and end of each chunk.

### Branch Name

tv4g2-issue2072-betterSchemaControl
